package com.salonplatform.domain.enums;

public enum WhatsAppTemplateCode {
    BILL_RECEIPT,
    PROMO_CAMPAIGN,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_REMINDER,
    BILL_WITH_FEEDBACK,
    SIGNUP_OTP,
    ACCOUNT_REGISTERED,
    REWARD_POINTS_EARNED,
    REWARD_POINTS_REDEEMED,
    MEMBERSHIP_EXPIRY_REMINDER,
    PACKAGE_EXPIRY_REMINDER,
    SERVICE_REMINDER,
    COUPON_OFFER,
    CUSTOMER_REFERRAL,
    EMPLOYEE_APPOINTMENT_NOTIFY
}
